// Resource
export const DELETE_ORDER = 'DELETE_ORDER'
export const CHANGE_ORDER_QUANTITY = 'CHANGE_ORDER_QUANTITY'

// Collection
export const ADD_ORDER = 'ADD_ORDER'

// Network
export const REQUEST_ORDERS = 'REQUEST_ORDERS'
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS'
export const INVALIDATE_ORDERS = 'INVALIDATE_ORDERS'
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const INVALIDATE_PRODUCTS = 'INVALIDATE_PRODUCTS'
