// Resource
export const DELETE_ORDER = 'DELETE_ORDER'
export const CHANGE_ORDER_QUANTITY = 'CHANGE_ORDER_QUANTITY'

// Collection
export const ADD_ORDER = 'ADD_ORDER'

// Authenticate
export const START_SESSION = 'START_SESSION'
export const END_SESSION = 'END_SESSION'

// Scanner
export const INITIALIZE_SCANNER = 'INITIALIZE_SCANNER'
export const START_SCANNING = 'START_SCANNING'
export const END_SCANNING = 'END_SCANNING'
export const FOUND_BARCODE = 'FOUND_BARCODE'

// Network
// - Orders
export const REQUEST_PROCESS_ORDERS = 'REQUEST_PROCESS_ORDERS'
export const RECEVIE_PROCESS_ORDERS = 'RECEVIE_PROCESS_ORDERS'
export const SUCCEED_PROCESS_ORDERS = 'SUCCEED_PROCESS_ORDERS'
export const FAIL_PROCESS_ORDERS = 'FAIL_PROCESS_ORDERS'

// - Products
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const INVALIDATE_PRODUCTS = 'INVALIDATE_PRODUCTS'
// - Cashiers
export const REQUEST_CASHIERS = 'REQUEST_CASHIERS'
export const RECEIVE_CASHIERS = 'RECEIVE_CASHIERS'
export const INVALIDATE_CASHIERS = 'INVALIDATE_CASHIERS'
// - Barcodes
export const REQUEST_BARCODES = 'REQUEST_BARCODES'
export const RECEIVE_BARCODES = 'RECEIVE_BARCODES'
export const INVALIDATE_BARCODES = 'INVALIDATE_BARCODES'
// - Session
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN'
export const FAIL_LOGIN = 'FAIL_LOGIN'
export const SUCCEED_LOGIN = 'SUCCEED_LOGIN'
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT'
